import 'package:eem/expense_manager.dart';

List<ExpenseManager> dummyData = [
  ExpenseManager(
    date: DateTime(2022, 5, 27),
    merchant: "Shuttle",
    total: 77.11,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 26),
    merchant: "Taxi",
    total: 44.78,
    status: "New",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 26),
    merchant: "Electronics",
    total: 125.44,
    status: "In Progress",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 26),
    merchant: "Fast Food",
    total: 22.85,
    status: "In Progress",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 26),
    merchant: "Shuttle",
    total: 300.77,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 25),
    merchant: "Restaurant",
    total: 244.45,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 25),
    merchant: "Ride Sharing",
    total: 669.77,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 25),
    merchant: "Hotel",
    total: 143.00,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 24),
    merchant: "Hotel",
    total: 140.51,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 24),
    merchant: "Shuttle",
    total: 656.96,
    status: "New",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 24),
    merchant: "Breakfast",
    total: 410.62,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 23),
    merchant: "Parking",
    total: 64.15,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 23),
    merchant: "Office Supply",
    total: 132.03,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 23),
    merchant: "Rental Car",
    total: 22.80,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 22),
    merchant: "Airline",
    total: 32.04,
    status: "New",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 22),
    merchant: "Breakfast",
    total: 90.39,
    status: "In Progress",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 22),
    merchant: "Parking",
    total: 521.48,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 22),
    merchant: "Electronics",
    total: 417.50,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 21),
    merchant: "Shuttle",
    total: 78.98,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 21),
    merchant: "Ride Sharing",
    total: 701.24,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 20),
    merchant: "Airline",
    total: 321.81,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 20),
    merchant: "Fast Food",
    total: 156.11,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 20),
    merchant: "Rental Car",
    total: 680.98,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 27),
    merchant: "Shuttle",
    total: 77.11,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 26),
    merchant: "Taxi",
    total: 44.78,
    status: "New",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 26),
    merchant: "Electronics",
    total: 125.44,
    status: "In Progress",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 26),
    merchant: "Fast Food",
    total: 22.85,
    status: "In Progress",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 26),
    merchant: "Shuttle",
    total: 300.77,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 25),
    merchant: "Restaurant",
    total: 244.45,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 25),
    merchant: "Ride Sharing",
    total: 669.77,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 25),
    merchant: "Hotel",
    total: 143.00,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 24),
    merchant: "Hotel",
    total: 140.51,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 24),
    merchant: "Shuttle",
    total: 656.96,
    status: "New",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 24),
    merchant: "Breakfast",
    total: 410.62,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 23),
    merchant: "Parking",
    total: 64.15,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 23),
    merchant: "Office Supply",
    total: 132.03,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 23),
    merchant: "Rental Car",
    total: 22.80,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 22),
    merchant: "Airline",
    total: 32.04,
    status: "New",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 22),
    merchant: "Breakfast",
    total: 90.39,
    status: "In Progress",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 22),
    merchant: "Parking",
    total: 521.48,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 22),
    merchant: "Electronics",
    total: 417.50,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 21),
    merchant: "Shuttle",
    total: 78.98,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 21),
    merchant: "Ride Sharing",
    total: 701.24,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 20),
    merchant: "Airline",
    total: 321.81,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 20),
    merchant: "Fast Food",
    total: 156.11,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
  ExpenseManager(
    date: DateTime(2022, 5, 20),
    merchant: "Rental Car",
    total: 680.98,
    status: "Reimbursed",
    comment: "Expense from my business trip",
  ),
];
